name: djdesigns
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54865
title: Dj Designs
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d203e'
    - '#4ba0fa'
    - '#fc3768'
    - '#fffefe'
    - '#fcbccc'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose:
  - name: awareness
    item: a8c5752b-cea2-4dc8-863f-6dcf77877855
    url: null
